services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: helloqdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped