services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - backingservice
    restart: unless-stopped

networks:
  backingservice:
    driver: bridge